//Specific business module: launchInstance
angular.module('instanceApp.services', ['ngResource'])
    .factory('instancesData', function($resource) {
      var data = {
      	code : 200,
      	"message": "OK",
      	data: [
      		{
      			id: 1,
      			name: "ABC",
	      		private_ip: "10.0.0.2",
	      		flavor_name: "m1.tiny",
	      		billing_type: "包月",
	      		status: "active",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.14", 
	      		key: "my sk1",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 1
      		},
      		{
      			id: 2,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 3,
      			name: "ACE",
	      		private_ip: "10.0.0.3",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "danger",
	      		ssh_desp: "sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.16", 
	      		key: "my sk3",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 3
      		},
      		{
      			id: 4,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 5,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 6,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 7,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 8,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 9,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 10,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 11,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 12,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 13,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 14,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 15,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 16,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 17,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 18,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 19,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 20,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 21,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 22,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 23,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 24,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 25,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 26,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 27,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 28,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 29,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 30,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 31,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 32,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 33,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 34,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 35,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 36,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 37,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 38,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 39,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 40,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 41,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 42,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 43,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 44,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 45,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 46,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 47,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 48,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 49,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},{
      			id: 50,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 51,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 52,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 53,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 54,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 55,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 56,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 57,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 58,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 59,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 60,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 61,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 62,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 63,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		},
      		{
      			id: 64,
      			name: "wawa",
	      		private_ip: "10.0.0.1",
	      		flavor_name: "m1.tiny",
	      		billing_type: "计时",
	      		status: "loading",
	      		ssh_desp: "wawawaaaa.sjdksdjls.sina.sws.com:121001",   
	      		floating_ips: "124.114.110.15", 
	      		key: "my sk2",
	      		security_group: "sg1",
	      		image: "centOS 64", 
	      		snap: 2
      		}
      		
      	]
      }

	  var instancesData = {};
	  
	  instancesData.query = function(cb){
	  	  instancesData = data.data;
	      return instancesData;
	  };
 
      instancesData.update = function(cb) {
        //return Project.update({id: this._id.$oid},angular.extend({}, this, {_id:undefined}), cb);
      };
 
      instancesData.destroy = function(cb) {
        //return Project.remove({id: this._id.$oid}, cb);
      };
 
      return instancesData;
    });